# Generated by Django 4.0.3 on 2022-04-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
